### PR TITLE
Change findDOMNode to react-dom

### PR DESCRIPTION
**Pull request by rogeriopvl**
This change removes warnings in react 0.14

### CODE REVIEW

**Comment by vasanthk** [comment]
Thanks @rogeriopvl :+1:

**Comment by wdmtech** [comment]
Any way to get the latest release including this upate on npm? cheers!

**Comment by vasanthk** [comment]
@rogeriopvl @wdmtech Published to npm. :+1:

**Comment by wdmtech** [comment]
Awesome, thanks! :+1:

**Pull request merged**
